version: '3.8'
services:
  php-backend:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: workanasoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
